# Generated by Django 4.0.5 on 2022-06-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseAvanzada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre3', models.CharField(max_length=40)),
                ('apellido3', models.CharField(max_length=40)),
                ('email3', models.EmailField(max_length=40)),
                ('celular3', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClaseInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre1', models.CharField(max_length=40)),
                ('apellido1', models.CharField(max_length=40)),
                ('email1', models.EmailField(max_length=40)),
                ('celular1', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClaseIntermedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre2', models.CharField(max_length=40)),
                ('apellido2', models.CharField(max_length=40)),
                ('email2', models.EmailField(max_length=40)),
                ('celular2', models.IntegerField()),
            ],
        ),
    ]
