# Generated by Django 4.0.5 on 2022-07-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoFinalApp', '0002_rename_apellido3_claseavanzada_apellido3_clase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=20)),
                ('imagen', models.ImageField(upload_to='')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
