# Generated by Django 4.0.5 on 2022-07-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoFinalApp', '0003_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='imagen',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='items',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
    ]
